language: python
python:
- '3.5'
install: pip install -r requirements.txt
script:
- make github
branches:
  only:
  - regis
env:
  global:
  - secure: "WZwwUcDDXZW0rp/R00GjOy/825fBZB8/PTORELRSp0fg1/lETHjIW1Yw6anfeVGQT73x+Sf3l2W2pbeTrvcomRGAGdI+RmKVzUuYXQrgGS+Pca+RLMk291uIRPaNwI63ZsjDd5uFxF8o8/SGc1CNrNvir+y4/OutJLt0Jx8uZBDdLq062bBsghwEhLFCa7ZN+dATQ5a/C/H4WQvV+J6WxHg6gqC1bNb6cnhnvKyX2vvF39tDCdZsPXRP6JQYBS8toYHKvaa6gN6WZ5B4sR/VQYBpiSE7xZMF+Q+oC25UPLhAjOXLKKvJPOg00bkzkrXMcv6N3QykQHE/eapA8aYcMNrNXi+mnSkZ00q2SKcEZ0cdtLpqKPHay5ufRCZVtFDns4A8gP7+CiWSfDemHQNdUS/ibHWvmnE5Prx7pfMHYcOOXOT1Rn9BJRHeAQ1/ZK54uki+zzRMRKzlifzmyE3KW8T+Rb93X9oeLEHlD3PICc7EfX5DekQe8qlZlKYw2PlsB+2AG3LuzyG8NMbicMZi27OprlWwvvU+Ug3xtyEdma8U693AX47/nzcWLlFS/SqoU0ARMgw94wu4gXO8iMttZpVVOa7njGNQfPeIuVjZmKEUxpzEaAKl8FN0Wzm70cvpfgu5t2sE3tUopHYLUhNns9e5Qdrk+/pLDKOM5rc2TAg="
